### ISSUE TITLE
App shouldn't crash on live reload where there's a typo in the stylesheet

### ISSUE THREAD

**Issue by markrickert** [infinitered/rmq#249]
We're all human. We make typos and hit `CMD`+`S`. It would be nice if the app didn't crash if we accidentally save with a typo and the live reload system tried to reload the stylesheet.

Maybe this is one instance where we could use `method_missing` but only in debug mode with live reload is active and then output a big message to the user about how they have a typo?

**Comment by twerth** [comment]
I think the problem here, and @jamonholmgren can correct me, is a capturing the except from the eval simply doesn't work.

If we could wrap every method in a begin block, perhaps that would work? We could do that by injecting the rescue block into the code when we read it before the eval. Just an idea.

**Comment by jamonholmgren** [comment]
I like @markrickert 's solution, actually. The exception only gets caught in development.
