### ISSUE TITLE
constant button on top of scrollView?

### ISSUE THREAD

**Issue by xikimay** [infinitered/rmq#301]
I know that is not an issue, but i was just wondering if it's possible with rmq to add a button on top of a scrollView and make the button remain in a constant position ?

thanks

**Comment by GantMan** [comment]
Append the button to the same superview as the scrollview.   That should work.

**Comment by xikimay** [comment]
Ok thanks for that , and over a TableScreen ?

**Comment by squidpunch** [comment]
You could put it in the table header. But if you want it on screen all the time. You'd probably have to attach it to the window rather than the controller view. 

If you do that remember that it's going to always be there unless removed. In other words navigating to another controller will still show this item attached at the window level unless you clean it up on any case another view is going to be rendered.

**Comment by xikimay** [comment]
Ok that was actually what i thought, anyway thank you for the answers :)
