### ISSUE TITLE
Getting iOS version error

### ISSUE THREAD

**Issue by Rubioli** [infinitered/rmq#325]
When I **run** `rake spec`, I get error says:

`ERROR! You are using RubyMotion Starter. Only iOS 9.3 is supported in this release. If you would like to target older or newer (in beta) versions of iOS you can purchase a paid subscription.`

What Can I do beside purchasing a paid subscription?

Thanks

**Comment by markrickert** [comment]
Hey @Rubioli, this is actually a RubyMotion error. You can see the different payment plans they offer here http://www.rubymotion.com/download/

You're probably on the free version which doesn't work with the latest iOS SDKs. You'll need to download the iOS SDK 9.3 or lower in Xcode and then specify that in your rakefile... otherwise RubyMotion uses the most recent SDK you have in Xcode by default.

**Comment by andrewhavens** [comment]
@Rubioli In addition, you may be unnecessarily specifying a `app.deployment_target` in your RubyMotion project configuration (in your app's `Rakefile`). You can remove that line and your error should go away.
